[package]
name = "lolcow-fortune"
version = "0.1.13"
authors = ["David Knaack <davidkna@users.noreply.github.com>"]
edition = "2021"
license = "MIT OR Apache-2.0"
readme = "README.md"
repository = "https://github.com/davidkna/lolcow-fortune-rs"
description = "`fortunes` combined with `lolcat` and `cowsay`!"

[lib]
path = "src/lib.rs"

[[bin]]
name = "lolcow-fortune"
path = "src/main.rs"
required-features = ["build-binary"]

[features]
default = ["build-binary", "download"]
build-binary = [
  "dep:clap",
  "dep:directories",
  "dep:lcat",
  "dep:lcowsay",
]

download = [
  "dep:flate2",
  "dep:tar",
  "dep:ureq",
  "dep:rustls",
  "dep:rustls-graviola",
]

[dependencies]
# Lib
deku = "0.19.1"
fastrand = "2.3.0"
itertools = "0.14.0"
memchr = "2.7.6"
thiserror = "2.0.17"

# Binary
clap = { version = "4.5.48", features = ["derive", "wrap_help"], optional = true }
directories = { version = "6.0.0", optional = true }

# Download
flate2 = { version = "1.1.4", optional = true, default-features = false, features = ["rust_backend"] }
rustls = { version = "0.23.32", optional = true, default-features = false }
rustls-graviola = { version = "0.3.1", optional = true }
tar = { version = "0.4.44", optional = true }
ureq = { version = "3.1.2", optional = true, default-features = false, features = ["rustls-no-provider"] }

[dependencies.lcowsay]
version = "0.5.12"
path = "../lcowsay"
optional = true

[dependencies.lcat]
version = "0.7.16"
path = "../lcat"
optional = true
