[package]
name = "lolcow-fortune"
version = "0.1.8"
authors = ["David Knaack <davidkna@users.noreply.github.com>"]
edition = "2021"
license = "MIT OR Apache-2.0"
readme = "README.md"
repository = "https://github.com/davidkna/lolcow-fortune-rs"
description = "`fortunes` combined with `lolcat` and `cowsay`!"

[lib]
path = "src/lib.rs"

[[bin]]
name = "lolcow-fortune"
path = "src/main.rs"
required-features = ["build-binary"]

[features]
default = ["build-binary"]
build-binary = [
  "attohttpc",
  "clap",
  "directories",
  "flate2",
  "lcat",
  "lcowsay",
  "tar",
]

[dependencies]
# Lib
deku = "0.14.0"
fastrand = "1.8.0"
itertools = "0.10.5"
memchr = "2.5.0"
thiserror = "1.0.37"

# Binary
clap = { version = "4.0.11", features = ["derive", "wrap_help"], optional = true }
directories = { version = "4.0.1", optional = true }

# Download
attohttpc = { version = "0.23.0", optional = true, default-features = false, features = ["tls"] }
flate2 = { version = "1.0.24", optional = true, default-features = false, features = ["rust_backend"] }
tar = { version = "0.4.38", optional = true }

[dependencies.lcowsay]
version = "0.5.7"
path = "../lcowsay"
optional = true

[dependencies.lcat]
version = "0.7.11"
path = "../lcat"
optional = true
