name: Deploy
on:
  push:
    branches:
      - main
jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: google-github-actions/release-please-action@v3.1.4
        id: release
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          release-type: rust

      - name: Checkout
        if: ${{ steps.release.outputs.releases_created }}
        uses: actions/checkout@v3.0.0

      - name: Install stable toolchain
        if: ${{ steps.release.outputs.releases_created }}
        uses: actions-rs/toolchain@v1.0.7
        with:
          toolchain: stable
          profile: minimal
          override: true

      - name: Publish to crates.io
        if: ${{ steps.release.outputs.releases_created }}
        uses: actions-rs/cargo@v1.0.1
        with:
          command: publish
          args: --token ${{ secrets.CRATES_IO_TOKEN }}
