name: Format Workflow
on:
  push:
    paths: ["**.md", "**.toml", "**.js", "**.json", "**.ts"]
  pull_request:
    paths: ["**.md", "**.toml", "**.js", "**.json", "**.ts"]

jobs:
  dprint:
    name: Dprint [Formatter]
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: Setup | Checkout
        uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6.0.3
        with:
          persist-credentials: false
      - name: Docs | Format
        uses: dprint/check@9cb3a2b17a8e606d37aae341e49df3654933fc23 # v2.3
