name: Format Workflow
on:
  push:
    paths: ["**.md", "**.toml", "**.js", "**.json", "**.ts"]
  pull_request:
    paths: ["**.md", "**.toml", "**.js", "**.json", "**.ts"]

jobs:
  dprint:
    name: Dprint [Formatter]
    runs-on: ubuntu-latest
    steps:
      - name: Setup | Checkout
        uses: actions/checkout@3df4ab11eba7bda6032a0b82a6bb43b11571feac # v4
      - name: Docs | Format
        uses: dprint/check@v2.2
