name: Main workflow
on:
  push:
    paths-ignore:
      - "**.md"
  pull_request:
    paths-ignore:
      - "**.md"

jobs:
  build:
    name: Build Nix targets
    environment: ${{ github.ref == 'refs/heads/main' && github.repository == 'davidkna/lcat-rs' && 'production' || 'ci' }}
    strategy:
      matrix:
        os:
          - ubuntu-24.04
          - ubuntu-24.04-arm
          - macos-latest
    runs-on: ${{ matrix.os }}
    permissions:
      id-token: "write"
      contents: "read"
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          persist-credentials: false
          
      - uses: cachix/install-nix-action@616559265b40713947b9c190a8ff4b507b5df49b # v31.10.4
        with:
          github_access_token: ${{ secrets.GITHUB_TOKEN }}
          
      - uses: cachix/cachix-action@1eb2ef646ac0255473d23a5907ad7b04ce94065c # v17
        with:
          name: davidkna
          authToken: "${{ secrets.CACHIX_AUTH_TOKEN }}"
          
      - name: Run `nix flake check`
        run: nix flake check .
        
      - name: Run `nix build`
        run: nix build .